server: 
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/log.log
  Encoding: json
  level: debug
cars:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin
  dbName: car_sale_db
  sslMode: false
redis:
  host: localhost
  port: 6374
  password: admin
  db: 0
  minIdleConnection: 100
  poolSize: 5000
  poolTimeOut: 240 