server: 
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/log.log
  Encoding: json
  level: debug
cars:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: localhost
  port: 6379
  password: admin
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeOut: 240 
  idleTimeOut: 500
  idleCheckFrequency: 500 
password:
  includeChart: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true